### ISSUE TITLE
Feature wishlist - support for amino acid alignments?

### ISSUE THREAD

**Issue by syueqiao** [maickrau/GraphAligner#108]
Hi! I have been using this tool to do sequence-graph alignments between a reference sequence and fragmented assemblies (I'm trying to retrieve a full novel gene through traversing graph paths), and it's been super helpful for sequences that have high nucleotide identity to my references (80-90+%). 

I also have some sequences that are in the 50% _amino acid_ identity range, which become too diverged to use nucleotide alignment for sequence-graph alignment. I was wondering if it would be possible to implement a feature that accepts amino acid sequences as input reference? (I am not too familiar with tool development so maybe this is an impossible ask 😅)

**Comment by maickrau** [comment]
Unfortunately GraphAligner cannot support amino acid alignment. Good amino acid alignment requires an alignment method where different types of substitutions have different scores, but GraphAligner uses Myers' bitvector algorithm which cannot support different scores for different substitutions. Possibly one of these tools might be useful: https://github.com/fawaz-dabbaghieh/PanPA https://github.com/lh3/miniprot

**Comment by syueqiao** [comment]
Thanks so much for taking the time to let me know! Will look into both of those tools :)
