### ISSUE TITLE
Support GFA with sequences from a FASTA file [feature request]

### ISSUE THREAD

**Issue by mrvollger** [maickrau/GraphAligner#12]
I think it would be great if the sequences of the GFA file could be contained in a fasta file with the same prefix. 

Basically if the GFA has * in place of the sequence tag look for a `.fasta` or `.fa` with the same prefix and load in the sequence from that. 

This is basically the same request as described here:
https://github.com/rrwick/Bandage/issues/23

Thanks!
Mitchell

**Comment by ekg** [comment]
I think this would warrant a script to out the FASTA sequences in the GFA.
What's the advantage of keeping them separate?

**Comment by mrvollger** [comment]
Hi Erik,

I was thinking for the input graph not any output. For example when Canu generates a GFA it's "S" lines just have "*" for seqs and there is an matching fasta file that contains the sequences. I think it would be useful to be able to directly use Canu's output without having to run an additional script to make a GFA that has the seq fields populated.

Does that make sense? 

Best,
Mitchell

**Comment by ekg** [comment]
In my experience, Canu's output isn't even correct. It's overlaps aren't
accurate and must be recalculated.

I think a preprocessing step is much nicer than putting this into
GraphAligner.

Alternatively, Canu could produce complete and correct GFA output. Have you
asked them about this?

**Comment by mrvollger** [comment]
Fair enough. However, given that multiple assemblers (Canu, Abyss) output GFAs with `*` and that is valid by the GFA spec, I think there should be some error throw when the input GFA is missing the seq field. The current output is: 
```
GraphAligner bioconda 1.0.10-
GraphAligner bioconda 1.0.10-
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 3)
Aborted (core dumped)
```
and it took me a while to track down the input issue.  Would you agree with that?

Also out of curiosity, do you know if the issues you just mentioned with the Canu GFA also extend to the `{prefix}.unitigs.gfa` file? I knew that `{prefix}.contig.gfa` had issues and it was removed in 1.9 but not that unitigs might have issues.

**Comment by maickrau** [comment]
Hi Mitchell,

The crash is definitely a bug and it should output something more helpful. I'd prefer a preprocessing approach to handle the * nodes. Do you know if any tools other than Canu & Abyss output this kind of graph?

**Comment by maickrau** [comment]
Commit 0b38cec prints a more helpful error message for nodes with *

**Comment by mrvollger** [comment]
Thanks! I am not aware of any other assemblers that use the `*` but there could be.

**Comment by mrvollger** [comment]
FYI, I have found that FALCON also uses a "*" in place of contigs in `asm.gfa`, but I think the error message is a good solution so I will close this.
