### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by MichelMoser** [maickrau/GraphAligner#2]
Hi, i would like to run the Snakemake pipeline to error-correct nanopore data but fail at the UntipRelative-step as there is no such binary available in my conda environment. 

I installed GraphAligner and dependencies via conda. 
Also tried to install GraphAligner manually as suggested but ran into some errors:
```
src/vg.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 incompatible with your Protocol Buffer headers. Please update
your headers.
make: *** [obj/AlignerMain.o] Error 1

```

Is there an alternative way i manage to get the UntipRelative binaries? 

Thanks, 
Michel

**Comment by maickrau** [comment]
Hi,

The pipeline indeed uses scripts which are not in the bioconda release. I've added a note in the readme until we have a better solution.

The compilation issue sounds troubling. Are you sure that you used the conda environment as suggested in the main readme, ie `conda env create -f CondaEnvironment.yml` and `source activate GraphAligner`? Can you try running `protoc --version`?

Best regards,
Mikko

**Comment by MichelMoser** [comment]
Hi, 

I am pretty sure i use the suggested env. 
Protoc:
```
$ protoc --version
libprotoc 3.6.0
```

**Comment by maickrau** [comment]
Protoc version looks fine. Can you try `pkg-config --modversion protobuf`? Do you have any protobuf versions installed outside the environment?

**Comment by MichelMoser** [comment]
```
$ pkg-config --modversion protobuf
3.6.0
```
no protobuf is actually only present in the GraphAligner env

**Comment by maickrau** [comment]
Protobuf version looks fine as well. Can you try this test program:
```
#include <google/protobuf/stubs/common.h>
#include <iostream>
int main()
{
	std::cout << GOOGLE_PROTOBUF_VERSION << std::endl;
	std::cout << GOOGLE_PROTOBUF_MIN_PROTOC_VERSION << std::endl;
}
```
Compile with ``g++ -std=c++11 `pkg-config --cflags protobuf` -Wl,-Bstatic `pkg-config --libs protobuf` -static-libstdc++ protobuftest.cpp`` and print the output

**Comment by MichelMoser** [comment]
```
$ g++ -std=c++11 `pkg-config --cflags protobuf` -Wl,-Bstatic `pkg-config --libs protobuf` -static-libstdc++ test.c

$ ./a.out
3006000
3006000

```

**Comment by MichelMoser** [comment]
Forgot to mention that i work on a cluster, so OS is Centos: 
```
]$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```
Might this create the problem?

**Comment by maickrau** [comment]
This is very strange. The macro in the test program should be exactly the same version that vg.pb.h checks. Can you double check that your src/vg.pb.h has `#if GOOGLE_PROTOBUF_VERSION < 3006000` in line 11?

**Comment by MichelMoser** [comment]
No it actually got `
  11 #if GOOGLE_PROTOBUF_VERSION < 3006001
`

**Comment by MichelMoser** [comment]
so should i change that?

**Comment by maickrau** [comment]
Ok, so something went strange in the protoc. Can you try first `make clean` and `make src/vg.pb.h` and see if the version in the file changes to 3006000

**Comment by MichelMoser** [comment]
yep, it changed to: 
```
  11 #if GOOGLE_PROTOBUF_VERSION < 3006000
```

**Comment by maickrau** [comment]
Ok, now `make all` should work

**Comment by MichelMoser** [comment]
Nice, it compiled.
But i still dont see a binary called `UntipRelative `. Do i have to compile it seperately?

**Comment by maickrau** [comment]
It should be in the bin/ directory as long as you used `make all`. It doesn't install it so you have to include the path.

**Comment by MichelMoser** [comment]
hmm, i just got: 

```
 bin]$ ls
ExtractPathSequence  GraphAligner  MafToAlignment  ReverseReads  SimulateReads  SupportedSubgraph
```

**Comment by maickrau** [comment]
That's strange again. Can you try separately compiling it with `make bin/UntipRelative`? You might need to do the same with `make bin/ExtractCorrectedReads` and `make bin/ExtractPathSequence`. I've no idea why make all wouldn't compile those though.

**Comment by MichelMoser** [comment]
looks like compiling fails for the ExtractPathSubgraphNeighbourhood binary, so only all binaries afterwards dont get compiled if i follow line `101` in the makefile. 
 ```
all: $(BINDIR)/GraphAligner $(BINDIR)/SimulateReads $(BINDIR)/ReverseReads $(BINDIR)/SupportedSubgraph $(BINDIR)/MafToAlignment $(BINDIR)/ExtractPathSequence $(BINDIR)/ExtractPathSubgraphNeighbourhood $(BINDIR)/VisualizeAlignment $(BINDIR)/NodePosCsv $(BINDIR)/ExtractExactPathSubgraph $(BINDIR)/EstimateRepeatCount $(BINDIR)/PickMummerSeeds $(BINDIR)/SelectLongestAlignment $(BINDIR)/Postprocess $(BINDIR)/AlignmentSubsequenceIdentity $(BINDIR)/BruteForceExactPrefixSeeds $(BINDIR)/PickAdjacentAlnPairs $(BINDIR)/ExtractCorrectedReads $(BINDIR)/UntipRelative $(BINDIR)/UnitigifyDBG
```


```
src/ExtractPathSubgraphNeighbourhood.cpp: In function 'int main(int, char**)':
src/ExtractPathSubgraphNeighbourhood.cpp:36:49: warning: narrowing conversion of '(&(& pos)->vg::Mapping::position())->vg::Position::node_id()' from 'google::protobuf::int64 {aka long int}' to 'int' inside { } [-Wnarrowing]
    queue.emplace(NodePos {pos.position().node_id(), pos.position().is_reverse()}, 0);
                           ~~~~~~~~~~~~~~~~~~~~~~^~
src/ExtractPathSubgraphNeighbourhood.cpp:45:57: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (distance.count(top.pos) == 1 && distance[top.pos] <= top.priority) continue;
/mnt/users/michelmo/.conda/envs/GraphAligner/lib/libprotobuf.a(gzip_stream.o): In function `google::protobuf::io::GzipInputStream::~GzipInputStream()':
gzip_stream.cc:(.text+0x136): undefined reference to `inflateEnd'
/mnt/users/michelmo/.conda/envs/GraphAligner/lib/libprotobuf.a(gzip_stream.o): In function `google::protobuf::io::GzipInputStream::Inflate(int)':
gzip_stream.cc:(.text+0x337): undefined reference to `inflate'
gzip_stream.cc:(.text+0x3ea): undefined reference to `inflateInit2_'
/mnt/users/michelmo/.conda/envs/GraphAligner/lib/libprotobuf.a(gzip_stream.o): In function `google::protobuf::io::GzipInputStream::Next(void const**, int*)':
gzip_stream.cc:(.text+0x4e1): undefined reference to `inflateEnd'
gzip_stream.cc:(.text+0x527): undefined reference to `inflateInit2_'
/mnt/users/michelmo/.conda/envs/GraphAligner/lib/libprotobuf.a(gzip_stream.o): In function `google::protobuf::io::GzipOutputStream::Init(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)':
gzip_stream.cc:(.text+0x618): undefined reference to `deflateInit2_'
/mnt/users/michelmo/.conda/envs/GraphAligner/lib/libprotobuf.a(gzip_stream.o): In function `google::protobuf::io::GzipOutputStream::Deflate(int)':
gzip_stream.cc:(.text+0x713): undefined reference to `deflate'
/mnt/users/michelmo/.conda/envs/GraphAligner/lib/libprotobuf.a(gzip_stream.o): In function `google::protobuf::io::GzipOutputStream::Close()':
gzip_stream.cc:(.text+0x9de): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
make: *** [bin/ExtractPathSubgraphNeighbourhood] Error 1


```

**Comment by maickrau** [comment]
Can you try pulling the most recent commit now and try `make all` again?

**Comment by MichelMoser** [comment]
I did and it finished compiling without error. 
Now i just need to adjust snakemake and everything should work perfectly. 
Thank you very much for the debugging and help!
