### ISSUE TITLE
Can't align HiFi reads to the graph constructed using minigraph

### ISSUE THREAD

**Issue by wwliao** [maickrau/GraphAligner#27]
Hi,

I'm trying to align HiFi reads to a graph constructed using minigraph.
GraphAligner works well on the subgraph with one or two chromosomes, but it doesn't work on the full graph and will interupt with the following messages:

> sdsl::int_vector<<anonymous> >::reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) [with unsigned char t_width = 0; sdsl::int_vector<<anonymous> >::reference = sdsl::int_vector_reference<sdsl::int_vector<0> >; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]: Assertion `idx < this->size()' failed.

The full graph I used can be downloaded from ftp://ftp.dfci.harvard.edu/pub/hli/minigraph/HPP/obsolete/GRCh38-CHM13-HPP58-0.12i.gfa.gz

Thanks,
Wen-Wei

**Comment by maickrau** [comment]
Hi Wen-Wei, I couldn't reproduce the crash. Could you please also upload the reads you were trying to align, and tell the exact version and command you used?

**Comment by wwliao** [comment]
Hi Mikko,

I just emailed you the links.

Thanks,
Wen-Wei

**Comment by ekg** [comment]
How did you fix this?

**Comment by wwliao** [comment]
Actually I still can't get it to run on the cluster at WashU, but this issue is gone on the cluster at Yale.

**Comment by jzhang-dev** [comment]
I got the same error when aligning ONT reads to a DBG. See detailed error message below:

```
GraphAligner bioconda 1.0.19-
GraphAligner bioconda 1.0.19-
Load graph from data/bcalm/HG002_MGISEQ/k=51/reference.dbg.gfa
Build alignment graph
Build minimizer seeder from the graph
GraphAligner: /home/zhangjiayuan/workspace/Alder/.snakemake/conda/fadfd70e68957df3eb7f3b74a04d8124_/include/sdsl/int_vector.hpp:1351: sdsl::int_vector<<anonymous> >::reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) [with unsigned char t_width = 0; reference = sdsl::int_vector_reference<sdsl::int_vector<0> >; size_type = long unsigned int]: Assertion `idx < this->size()' failed.
```

Any help would be appreciated.
