### ISSUE TITLE
considerations for large consensus genome graphs

### ISSUE THREAD

**Issue by ekg** [maickrau/GraphAligner#30]
The consensus graphs from pggb are designed to be used by alignment tools like GraphAligner. They have large nodes, and simple topology. So we're testing GraphAligner but I had a question about the preparation of the graph. Is it beneficial to sort the graph topologically, so as to improve seeding?

**Comment by maickrau** [comment]
The node ordering or names won't matter. GraphAligner internally finds "mostly acyclic" subgraphs based on the graph topology and then seeds along those.

**Comment by ekg** [comment]
Thanks, it's great to know it's doing that.
