### ISSUE TITLE
Equivalent alignment handling

### ISSUE THREAD

**Issue by jnvaughn** [maickrau/GraphAligner#32]
How does GraphAligner handle equivalent alignments at two position in the graph: random placement, etc?  Also, is there a way to report mapping quality information?  Thanks!

**Comment by maickrau** [comment]
By default equivalent alignments are randomly placed and there is no mapping quality. In the latest commit in master you can use a hidden experimental parameter "--multiseed-DP 1" which reports all equivalent alignments and also has mapping qualities, but that's still experimental so it might give unexpected results in some cases.

**Comment by jnvaughn** [comment]
Great.  We use this parameter quite heavily but will keep a look out for odd behavior and post here.  Thank you again and great tool.

**Comment by maickrau** [comment]
Versions 1.0.14 and later have mapping qualities and report all equivalently good alignments
