### ISSUE TITLE
Interpretation of log output on aligned base pairs

### ISSUE THREAD

**Issue by tobiasmarschall** [maickrau/GraphAligner#35]
Hi Mikko,

we were unsure how to interpret the log out put with respect to the number of bp aligned: 

```
Input reads: 1689007 (43919966320bp)
...
Alignments: 6934171 (42899288374bp) (39634694 additional alignments discarded)
```

Can the alignments overlap in the space of individual reads? That is, is it valid to divide the bp in input reads by the bp aligned to get the fraction of basepairs that in the input that are involved in alignments? (Sorry if I just missed that. But might be useful for users to hint at this in the output).

Cheers,
Tobias

**Comment by maickrau** [comment]
The alignments can overlap for individual reads. Dividing the aligned bp by input bp will be an overestimate in that case. Usually the alignments shouldn't overlap by too much unless "--all-alignments" is set so it will be only a slight overestimate.

**Comment by tobiasmarschall** [comment]
Ok, thanks for clarifying this.

**Comment by ekg** [comment]
The rs-peanut tool used in pgge can correct for this effect.
