### ISSUE TITLE
Loading graph fail:  'std::out_of_range'

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [maickrau/GraphAligner#36]
Hello,

I'm trying to use GraphAligner and I get the following :

```
GraphAligner bioconda 1.0.12-
GraphAligner bioconda 1.0.12-
Load graph from spade_hybrid_assembly/assembly/assembly_graph_with_scaffolds.gfa
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
/bin/bash: line 1: 12612 Aborted                 (core dumped) GraphAligner -g spade_hybrid_assembly/assembly/assembly_graph_with_scaffolds2.gfa -f /home/sebr/seb/Database/Fungus_DB/FRE_consensus_2_3_6_7.fas -a spade_hybrid_assembly/graphaligner/18S.gaf -t 100 -x dbg --high-memory

```

It looks like an issue with loading the graph. So some context, I'm using the conda install and the files from the test folder work. The graph is from a spade assembly and should be quite big, 1 of the component is at 5 millions contigs. 

Any idea what could be make it work?

**Comment by maickrau** [comment]
Hi, could you please upload the graph?

**Comment by maickrau** [comment]
GraphAligner had an issue with reading node IDs that are integers but too big to fit in 32 bits. Could you try again with commit ba87396?

**Comment by maickrau** [comment]
This should now work in version 1.0.13. If it happens again, please re-open or create a new issue.
