### ISSUE TITLE
GfaGraph.cpp assertion failed when loading recent VG based GFA

### ISSUE THREAD

**Issue by brianabernathy** [maickrau/GraphAligner#37]
I've noticed a recent change in GFA graphs produced by VG. Previously, the path record overlaps field contained segment lengths and link record overlaps were set to '0M'. Recent versions of VG now produce path and link overlaps of '*'. This results in the error below when running GraphAligner.

GraphAligner: src/GfaGraph.cpp:271: static GfaGraph GfaGraph::LoadFromStream(std::istream&, bool, bool): Assertion `dummyc == 'M' || (dummyc == 'S' && overlap == 0)' failed.

If I manually set GFA link record overlaps to '0M', GraphAligner parses the file successfully.

**Comment by maickrau** [comment]
Starting with commit cc4562c GraphAligner will now assume that overlaps of "*" are "0M"

**Comment by brianabernathy** [comment]
Great, thanks for the quick fix.
