### ISSUE TITLE
Explicit definition of default "-x vg" and "-x dbg" parameters

### ISSUE THREAD

**Issue by briannadon** [maickrau/GraphAligner#38]
I would like to tweak parameters to get better alignments for my projects, but using "-x vg" for example doesn't explicitly tell me what the "-b", "-B", "-c" etc parameters are for these presets, and I can't seem to find documentation of that.  Can you tell us what they are, and/or add a little blurb in the help text that describes what these presets are equivalent to?

**Comment by maickrau** [comment]
That's a good idea, I'll add that to the help message in the next version. In v1.0.13 `-x vg` is equivalent to `--seeds-minimizer-density 10 --seeds-minimizer-length 15 --seeds-minimizer-windowsize 20 --seeds-extend-density -1 --seeds-minimizer-ignore-frequence 0.001 -b 10` and `-x dbg` is `--seeds-minimizer-density 5 --seeds-minimizer-length 19 --seeds-minimizer-windowsize 30 --seeds-extend-density 0.002 -b 5 -C 10000`
