### ISSUE TITLE
overlap longer than nodes error

### ISSUE THREAD

**Issue by ptrebert** [maickrau/GraphAligner#43]
Hi Mikko,
I just stumbled upon this again (v1.0.13 from conda) and wanted to investigate the size of the problem in the input graph when I encountered the following:

- node A is 334822 bp
- node B is 18475 bp
- link between A and B has an overlap of "18472M"

Why does GA think the overlap is too long?

+Peter

**Comment by maickrau** [comment]
Hi, could you upload the graph?

**Comment by ptrebert** [comment]
Yes, of course - would sharing the graph via Globus work for you?

One more observation: I just extracted the two nodes and the edge, and used only that as input for GA (same reads); this time, the error was not triggered (I get lots of failed Assertions instead, but I assume that is a result of the tiny graph size)

**Comment by maickrau** [comment]
Yes, Globus works

**Comment by maickrau** [comment]
The graph has two edges with different overlaps between the two nodes:
```
L       utg010491l      -       utg042014l      +       18478M  L1:i:316344
L       utg042014l      -       utg010491l      +       18472M  L1:i:3
```
and one of them is longer than utg042014l

**Comment by ptrebert** [comment]
ah, I missed the second one - any chance GraphAligner could print the actual edge entry in the error message?

**Comment by ptrebert** [comment]
@maickrau 
Can you make explicit what the intended behavior is: apparently, GraphAligner checks for an overlap difference "> 0" between edge and node, i.e. edges that have the same length as the shorter node (overlap difference = 0) are considered invalid and that is as intended?

**Comment by maickrau** [comment]
Yes, edges where the overlap is as long or longer than the shorter node are considered invalid. Only edges where the overlap is shorter than both nodes are valid.

**Comment by ptrebert** [comment]
Ok, thanks for confirming, I'll adapted my GFA cleanup script accordingly.
