### ISSUE TITLE
release 1.0.14 is not available in bioconda

### ISSUE THREAD

**Issue by ptrebert** [maickrau/GraphAligner#51]
I see that the recipe has been updated and the respective PR accepted, but GraphAligner v1.0.14 does not show up in bioconda (for me as well as others). Can you please check why the new release is not available? Thanks.

+Peter

**Comment by maickrau** [comment]
Works now, see https://github.com/bioconda/bioconda-recipes/issues/32369

**Comment by ptrebert** [comment]
great, thanks
