### ISSUE TITLE
Error: Alignment broke with some reads.

### ISSUE THREAD

**Issue by AntoineHo** [maickrau/GraphAligner#52]
Hello,

I am trying to align MinION reads to a .gfa graph obtained with Flye. Some reads caused the alignement to break with this stderr:

```
GraphAligner bioconda 1.0.14-
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: read1. Seed: 0+,0,0,0
```

I do not really understand what is wrong with the reads, I attached a .fq file of one read that cause this error. Is this a problem in the formatting of the fastq file?

Cheers,
Antoine

[failed_minion_read_graphaligner.fq.txt](https://github.com/maickrau/GraphAligner/files/7920183/failed_minion_read_graphaligner.fq.txt)

**Comment by maickrau** [comment]
The formatting of the fastq file is fine. This looks like a bug in GraphAligner instead. Could you also add the graph here?

**Comment by AntoineHo** [comment]
No problems,

Here is the file containing the graph (~3Gb): https://www.dropbox.com/s/m8039sxxkgutt8z/assembly_graph.gfa.gz?dl=0

**Comment by AntoineHo** [comment]
I just tried to align one of the problematic reads with the previous version of GraphAligner (v1.0.13) and it worked without error. I will try the whole dataset now.

**Comment by maickrau** [comment]
This should now work with the most recent commit, please open a new issue if it happens again.
