### ISSUE TITLE
Evaluate the Performance of sequence-to-graph mapping in GraphAligner.

### ISSUE THREAD

**Issue by gsc74** [maickrau/GraphAligner#57]
I want to evaluate the Performance of sequence-to-graph mapping as shown in `Table 2` in [minigraph](https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-020-02168-z.pdf), for both `minigraph` and `GraphAligner`, I'm able to get numbers for minigraph with using `paftools.js mapeval minigraph_output.gaf`. [[paftools.js]](https://github.com/lh3/minimap2/tree/master/misc)
Output:
`Q	60	2778043	13768	0.004956007	       2778043 `
`Q	59	         828	         7	0.004957049	       2778871 `
`Q	58	         794	        6	0.004957792 	2779665`
`Q	57	         754	         6	0.004958605	2780419`
`Q	56	         838	         5	0.004958909	2781257`
`Q	55	         756	          4	0.004958999	2782013`
`........`
`........`
While using same command  `paftools.js mapeval GraphAligner_output.gaf`
Output :
`Q	60	2907330	2907330	1.000000000	2907330`
`Q	58	              1	             1	1.000000000	2907331`
`Q	56	            18	           18	1.000000000	2907349`
`............`
`.............`
@maickrau , I want to know what is the difference between `gaf` output of `minigraph` and `GraphAligner`, and why `paftools.js` is giving right numbers for `minigraph` while wrong numbers for `GraphAligner`. How do i evaluate number of `unmapped reads` and `wrong mappings` in `GraphAligner`.

**Comment by ekg** [comment]
This might be a question to ask the paftools author, who made the table in question.
