### ISSUE TITLE
Mapping long reads to HGSVC graph

### ISSUE THREAD

**Issue by jiadong324** [maickrau/GraphAligner#61]
Dear author,

I am trying to align long reads to HGSVC graph ([HGSVC_hs38d1.vg](https://cgl.gi.ucsc.edu/data/giraffe/mapping/graphs/for-NA19240/hgsvc/hs38d1/HGSVC_hs38d1.vg)) used in Giraffe paper. 

Error message is:
```
GraphAligner bioconda 1.0.16-
Load graph from ./HGSVC_hs38d1.gfa
Error in the graph: Unspecified edge overlaps (*) are not supported
```
Is that mean the graph contain overlapped edges?

Thanks!

**Comment by maickrau** [comment]
The graph has edges which don't have overlaps specified. GraphAligner requires that all edges explicitly specify the overlap. If it's a vg graph then the edges most likely should have no overlap but you should confirm this with the people who made the graph. In case the edges do have no overlap, you can replace the unspecified edge overlaps with zero overlap using the following awk command:

```
awk 'BEGIN{OFS=FS="\t";}$1!="L"||$6!="*"{print;}$1=="L"&&$6=="*"{$6="0M";print;}' < HGSVC_hs38d1.gfa > HGSVC_hs38d1-fix.gfa
```

**Comment by jiadong324** [comment]
Thanks! This works now!
