### ISSUE TITLE
Error related to protobuf in installing GraphAligner

### ISSUE THREAD

**Issue by wzboy1984** [maickrau/GraphAligner#62]
Hi, 

When I compiled GraphAligner with miniconda3, I encountered the following problem. Error information are shown below.

> /home/wangz/miniconda3/envs/GraphAligner/bin/x86_64-conda-linux-gnu-c++ -c -o obj/AlignerMain.o src/AlignerMain.cpp -Wall -Wextra -std=c++17 -O3 -g -Iconcurrentqueue -IBBHash -Izstr/src -Iparallel-hashmap/parallel_hashmap/ `pkg-config --cflags protobuf` `pkg-config --cflags libsparsehash` -Wno-unused-parameter -IMEMfinder/src -I`jemalloc-config --includedir` -DVERSION="\"Branch master commit 823ad4b05378436625fad9ea564b2dd0de1647c5 2022-05-12 16:47:48 +0200\""
> In file included from src/Aligner.h:7,
>                  from src/AlignerMain.cpp:7:
> src/vg.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
>    17 | #error This file was generated by an older version of protoc which is
>       |  ^~~~~
> src/vg.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
>    18 | #error incompatible with your Protocol Buffer headers.  Please
>       |  ^~~~~
> src/vg.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
>    19 | #error regenerate this file with a newer version of protoc.
>       |  ^~~~~
> In file included from src/Aligner.h:7,
>                  from src/AlignerMain.cpp:7:
> src/vg.pb.h:27:10: fatal error: google/protobuf/inlined_string_field.h: No such file or directory
>    27 | #include <google/protobuf/inlined_string_field.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [makefile:38: obj/AlignerMain.o] Error 1

The error information show that "inlined_string_field.h" file of protobuf library doesn't exist.
I think that maybe the version of protobuf is wrong in conda, which is 3.14.0. And what is the right version of protobuf used in GraphAligner?

**Comment by maickrau** [comment]
The specific version should not be important as long as it's the exact same version for protoc and protobuf development libraries. The error message claims different versions were used even though it looks like you are using the conda environment which should have the same versions. Could you please activate the environment and then try `make clean && make all` just to double check that the vg.pb.* files get regenerated with the conda protoc version. If this doesn't work then try these and paste the output here:

```
conda list
which protoc
```
