### ISSUE TITLE
Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed.

### ISSUE THREAD

**Issue by ykkim0127** [maickrau/GraphAligner#67]
Hi.
I'm trying to run graphunzip using clr assembly with Hi-C and 10X Genomics data.
The problem is clr, when running Graphaligner this prints some "failed" lines as below but running for 5 or more days with 68GB gaf file. I wonder 1) what this means, 2) is it okay to use this gaf file for further analysis and 3) when it ends. The input for clr is about 148G.

src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/2426748/53596_62084. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/3735880/0_18706. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/4000373/0_20174. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/7602798/20181_41804. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/9374255/0_26356. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/9766432/5579_25226. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/9766522/53343_176379. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/14092620/0_5016. Seed: 0+,0,0,0
src/GraphAlignerBitvectorCommon.h:1118: Assertion 'previous.node(neighbor).endSlice.scoreEnd >= scoreHere-(eq?0:1)' failed. Read: m64062_191225_080113/16255005/0_33636. Seed: 0+,0,0,0
...

And I've used this command.
##For CLR
$GraphAligner -g assembly_graph.gfa -f Raw/m64062_m64032_subreads.fa -a m64062_m64032_2.gaf -t 64 -x vg

**Comment by maickrau** [comment]
Hi, this means that alignment failed for those specific reads which are listed in the log. The alignments for the other reads are not affected and you can use the gaf. The bug which causes the alignment to fail has been there for a while but I haven't been able to track it down.

**Comment by maickrau** [comment]
This should now be fixed in [857cbc1](https://github.com/maickrau/GraphAligner/commit/857cbc1288cb6def69248978639624fc0c6cfa1c)
