### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by tprodanov** [maickrau/GraphAligner#69]
I am trying to align long sequence to a rather simple graph and get an error
```bash
src/GraphAligner.h:150: Assertion 'params.graph.chainApproxPos[nodeIndex] + realOffset >= seedHits[i].seqPos' failed. Read: HG01978.2_0. Seed: 0+,0,0,0
```
I use version `bioconda 1.0.16-`
I selected a sequence that would fail with both `vg` and `dbg` presets:
```bash
GraphAligner -g graph.gfa -f read.fasta -a out.gaf -x vg  # Fails
GraphAligner -g graph.gfa -f read.fasta -a out.gaf -x dbg # Fails
```
You can download the graph and the sequence [here (48 kb)](https://dl.dropboxusercontent.com/s/zl4l7iqsavb9suc/GraphAligner_bug.tar.gz).

**Comment by maickrau** [comment]
This was a bug in seed hit clustering which can happen if the read is longer than the total number of base pairs in the graph. It's now fixed in commit https://github.com/maickrau/GraphAligner/commit/29dc9333c769270213435384b169a97758156b77 and will be included in next bioconda release.

**Comment by tprodanov** [comment]
Thank you! I compiled the latest version and it produces no errors.
