### ISSUE TITLE
paf format error in some case

### ISSUE THREAD

**Issue by zhangyixing3** [maickrau/GraphAligner#74]
Dear Mr/Mrs, 
 I mapping HiFI data to pggb.gfa by GraphAligner. The parameter is **GraphAligner -g pggb.gfa -f reads_all.fasta.gz -a mapping_pggb.gaf -x vg -t 30**. I find  mapping_pggb.gaf  format is strange as below.
![QQ截图20230216132714](https://user-images.githubusercontent.com/91043462/219276525-3cfb7534-dd71-4cd0-bac6-1a39ce2c3f3f.png)
Finally, I found that the format error was caused by HIFI data. Could you  fix this problem in the future?

![QQ截图20230216133203](https://user-images.githubusercontent.com/91043462/219277189-d3481080-ac38-4f8d-893e-5ba76c024390.png)

Thank you very much .

**Comment by maickrau** [comment]
GraphAligner keeps the read name as is in the output. I'd recommend filtering the tags out of the input fasta with eg. `cut -f 1 < hifi.fa > hifi_no_tags.fa`. In this case you can also remove the tags from the gaf afterwards with `awk -F "\t" '{OFS="\t"}substr($2,1,5)!="rq:f:"{print;}substr($2,1,5)=="rq:f:"{$2=""; print $0;}' < mapping_pggb.gaf | sed 's/\t\t/\t/g' > mapping_pggb_no_tags.gaf`

**Comment by zhangyixing3** [comment]
Thank you for your help ! I have solved this problem.
