### ISSUE TITLE
Bug report: option parsing error

### ISSUE THREAD

**Issue by JianjunJin** [maickrau/GraphAligner#77]
## Test Data
 - the assembly graph file: [snp.graph.gfa.txt](https://github.com/maickrau/GraphAligner/files/10914521/snp.graph.gfa.txt)
 - a single-read file: [test_reads.11_13946.fastq.txt](https://github.com/maickrau/GraphAligner/files/10914522/test_reads.11_13946.fastq.txt)
 
## Error
```
GraphAligner -g snp.graph.gfa -f test_reads.11_13946.fastq -x vg -a test.gaf --seeds-mum-count -1
```
> GraphAligner bioconda 1.0.17-
GraphAligner bioconda 1.0.17-
pick only one seeding method
run with option -h for help

## Description
When I used the option `--seeds-mum-count -1`, GraphAligner died with the following error `pick only one seeding method`. 

## Temporary Solution
By looking at the code, I find a temporary solution to be turning off all other seeding methods, such as
```
GraphAligner -g snp.graph.gfa -f test_reads.11_13946.fastq -x vg -a test.gaf --seeds-mum-count -1 --seeds-mem-count 0 --seeds-minimizer-densit 0
```
> GraphAligner bioconda 1.0.17-
GraphAligner bioconda 1.0.17-
Load graph from snp.graph.gfa
Build MUM/MEM seeder from the graph
Build alignment graph
MUM seeds, min length 20
Seed cluster size 1
Extend up to 5 seed clusters
Alignment bandwidth 5, tangle effort 10000
Clip alignment ends with identity < 66%
X-drop DP score cutoff 14705
Backtrace from 10 highest scoring local maxima per cluster
write alignments to test.smd.mtc.gaf
Align
Alignment finished
Input reads: 1 (15009bp)
Seeds found: 183
Seeds extended: 2
Reads with a seed: 1 (15009bp)
Reads with an alignment: 1 (14824bp)
Alignments: 1 (14824bp)
End-to-end alignments: 0 (0bp)

Please let me know any other information you need.

**Comment by maickrau** [comment]
The preset `-x vg` already picks minimizer seeding, and then picking MUM seeding gives the error. You can indeed disable minimizer seeding by explicitly adding `--seeds-minimizer-density 0`. My recommendation is to either use a preset or completely custom parameters, but not mix them.
