### ISSUE TITLE
Optimal alignment

### ISSUE THREAD

**Issue by abanerjee10** [maickrau/GraphAligner#80]
What is the recommended method for doing optimal alignment with GraphAligner?

Does the hidden argument --seedless-DP accomplish this, and is there a faster option available?

**Comment by maickrau** [comment]
There's no option for doing guaranteed optimal alignment. You can try something like `--seedless-DP -b 100000 --precise-clipping 0.502 --X-drop 1000000` which should have a high probability of returning optimal alignments but not guaranteed.

**Comment by abanerjee10** [comment]
I see, I believed that guaranteeing optimal alignment was possible. Thank you for your help!
