### ISSUE TITLE
converting .gaf alignment to sequence

### ISSUE THREAD

**Issue by dcopetti** [maickrau/GraphAligner#81]
Hello,
I am new to handling graphs, so my question may be silly.
I have an assembly (Hifiasm) and PacBio CLR reads that I aligned to the graph to try to resolve some tangles and extend sequence in longer contigs/scaffolds.
My command was
`GraphAligner -t 100 -g assembly.p_utg_del.gfa -f CLR_subreads.fa.gz -a aln_reads.gaf -x dbg`
how can I use the information in the .gaf file to resolve contigs in the .gfa graph?
Thanks!

**Comment by maickrau** [comment]
I'm not aware of a standalone tool which would do this. You can try running verkko or hifiasm in hybrid mode using the CLR reads as nanopore reads. Depending on how long the CLR reads are this might improve the assembly. If the CLR reads are not much longer than hifi reads then they won't help though.

**Comment by dcopetti** [comment]
I run Hifiasm in hybrid mode, and there was no improvement in the assembly stats.
The CLR data has subread N50 of 27 kb (the HiFi reads are 14 kb), ~18x coverage, but I see that most of the Hifiasm contigs have 5-20 kb poly(AT) stretches at their ends. I assume that there will be very few CLRs that reach into unique sequence on both sides of the repeat.
I will give Verkko a try, thank you for the feedback!
