### ISSUE TITLE
How to map node id to corresponded allele id?

### ISSUE THREAD

**Issue by yipukangda** [maickrau/GraphAligner#85]
Hi,

I construct a pan-genome with pggb from an allele database, then align a simulated data to this PFA data, and get result gaf file.

if I want to fast map the `path match` (such as, ***>9705>9706>9707>9709>9711>9712***) to the most possible `allele id`(such as ***9705 -> genotype_3, 9706-> genotype_3,  9707-> genotype_5***), how could I achieve this.

thanks

**Comment by jjuhyunkim** [comment]
Hi ! 
Did you resolve your issue? How did you do it? I have the same issue.
