### ISSUE TITLE
Assertion issue

### ISSUE THREAD

**Issue by asylvz** [maickrau/GraphAligner#90]
Hi,

I'm trying to align an assembly to minigraph cactus using the command below. However I get the following error:
    
    GraphAligner -g hprc-v1.1-mc-chm13.gfa -f XXX.fasta.gz -a {output} -t 24 -- bandwidth 30 --multimap-score-fraction 0.99 
    --precise-clipping 0.9 --min-alignment-score 2000 --seeds-mem-count 100000 --seeds-mxm-windowsize 10000 
    --seeds-mxm-cache-prefix {output_path}/ga_prefix

However, this is the error I get:
   
    src/GraphAlignerBitvectorBanded.h:536: Assertion 'currentSlice.node(i).minScore <= 
    currentSlice.node(i).startSlice.scoreEnd' failed. Read: haplotype1-0000027. Seed: 0+,0,0,0

**Comment by maickrau** [comment]
Hi, could you upload the graph and the read?

**Comment by asylvz** [comment]
With lower bandwidth it got resolved but I cannot regenerate this issue currently. I will let you know if I see this again but now I have a similar issue with a different sample:

    GraphAligner -g hprc-v1.1-mc-chm13.gfa -f HG02953.vrk-ps-sseq.asm-hap2.fasta.gz -a HG02953_hap2.gaf -t 16 -- 
    bandwidth 15 --multimap-score-fraction 0.99 --precise-clipping 0.9 --min-alignment-score 2000 --seeds-mem-count 
    100000 --seeds-mxm-windowsize 10000 --seeds-mxm-cache-prefix snake_alignments/ga_prefix

And the error:

    src/GraphAligner.h:647: Assertion 'trace.trace[i].DPposition.seqPos == trace.trace[i-1].DPposition.seqPos || 
    trace.trace[i].DPposition.seqPos == trace.trace[i-1].DPposition.seqPos+1' failed. Read: haplotype2-0000154. Seed: 
    0+,0,0,0

Reads:
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC3/working/20230818_verkko_batch1/assemblies/HG02953/HG02953.vrk-ps-sseq.asm-hap2.fasta.gz

Graph:
https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.gfa.gz

**Comment by yuand2022** [comment]
![image](https://github.com/maickrau/GraphAligner/assets/168074997/37213466-0374-420e-9a60-02bb4d66fb30)
Yes, I also found a lot of assertions, I don’t know how to deal with it

**Comment by maickrau** [comment]
Version 1.0.20 now fixes some cases where these assertions happen. I'll close this issue and if the assertions still happen with 1.0.20 then please create a new issue.
